#define GL3_FUNC_DECL

#include "openGL.h"
#include "common\UTF.hpp"

//onde é carregado o módulo do DLL
static HINSTANCE openGLModule;

//para ajudar as coisas
#define GETADDR_NATIVE(var, name, type)  if ((var = (type)GetProcAddress(nativeOpenGLModule, name)) == nullptr) return false;
#define GETADDR_BASE(var, name, type)  if ((var = (type)wglProcAddressOpenGL(name)) == nullptr) return false;

//o protótipo para ajudar a passar a função de wglGetProcAdrress
typedef PROC (APIENTRY *PFNWGLGETPROCADDRESSPROC)(LPCSTR lpcstr);

//função para carregar tudo
static
bool loadGLFunctions(HINSTANCE nativeOpenGLModule, PFNWGLGETPROCADDRESSPROC wglProcAddressOpenGL)
{
	//tem de ser para ler os ponteiros das funções neste namespace
	using namespace HorseRadish::OpenGL;

	#ifdef GL_VERSION_1_0
	GETADDR_NATIVE(glCullFace, "glCullFace", PFNGLCULLFACEPROC);
	GETADDR_NATIVE(glFrontFace, "glFrontFace", PFNGLFRONTFACEPROC);
	GETADDR_NATIVE(glHint, "glHint", PFNGLHINTPROC);
	GETADDR_NATIVE(glLineWidth, "glLineWidth", PFNGLLINEWIDTHPROC);
	GETADDR_NATIVE(glPointSize, "glPointSize", PFNGLPOINTSIZEPROC);
	GETADDR_NATIVE(glPolygonMode, "glPolygonMode", PFNGLPOLYGONMODEPROC);
	GETADDR_NATIVE(glScissor, "glScissor", PFNGLSCISSORPROC);
	GETADDR_NATIVE(glTexParameterf, "glTexParameterf", PFNGLTEXPARAMETERFPROC);
	GETADDR_NATIVE(glTexParameterfv, "glTexParameterfv", PFNGLTEXPARAMETERFVPROC);
	GETADDR_NATIVE(glTexParameteri, "glTexParameteri", PFNGLTEXPARAMETERIPROC);
	GETADDR_NATIVE(glTexParameteriv, "glTexParameteriv", PFNGLTEXPARAMETERIVPROC);
	GETADDR_NATIVE(glTexImage1D, "glTexImage1D", PFNGLTEXIMAGE1DPROC);
	GETADDR_NATIVE(glTexImage2D, "glTexImage2D", PFNGLTEXIMAGE2DPROC);
	GETADDR_NATIVE(glDrawBuffer, "glDrawBuffer", PFNGLDRAWBUFFERPROC);
	GETADDR_NATIVE(glClear, "glClear", PFNGLCLEARPROC);
	GETADDR_NATIVE(glClearColor, "glClearColor", PFNGLCLEARCOLORPROC);
	GETADDR_NATIVE(glClearStencil, "glClearStencil", PFNGLCLEARSTENCILPROC);
	GETADDR_NATIVE(glClearDepth, "glClearDepth", PFNGLCLEARDEPTHPROC);
	GETADDR_NATIVE(glStencilMask, "glStencilMask", PFNGLSTENCILMASKPROC);
	GETADDR_NATIVE(glColorMask, "glColorMask", PFNGLCOLORMASKPROC);
	GETADDR_NATIVE(glDepthMask, "glDepthMask", PFNGLDEPTHMASKPROC);
	GETADDR_NATIVE(glDisable, "glDisable", PFNGLDISABLEPROC);
	GETADDR_NATIVE(glEnable, "glEnable", PFNGLENABLEPROC);
	GETADDR_NATIVE(glFinish, "glFinish", PFNGLFINISHPROC);
	GETADDR_NATIVE(glFlush, "glFlush", PFNGLFLUSHPROC);
	GETADDR_NATIVE(glBlendFunc, "glBlendFunc", PFNGLBLENDFUNCPROC);
	GETADDR_NATIVE(glLogicOp, "glLogicOp", PFNGLLOGICOPPROC);
	GETADDR_NATIVE(glStencilFunc, "glStencilFunc", PFNGLSTENCILFUNCPROC);
	GETADDR_NATIVE(glStencilOp, "glStencilOp", PFNGLSTENCILOPPROC);
	GETADDR_NATIVE(glDepthFunc, "glDepthFunc", PFNGLDEPTHFUNCPROC);
	GETADDR_NATIVE(glPixelStoref, "glPixelStoref", PFNGLPIXELSTOREFPROC);
	GETADDR_NATIVE(glPixelStorei, "glPixelStorei", PFNGLPIXELSTOREIPROC);
	GETADDR_NATIVE(glReadBuffer, "glReadBuffer", PFNGLREADBUFFERPROC);
	GETADDR_NATIVE(glReadPixels, "glReadPixels", PFNGLREADPIXELSPROC);
	GETADDR_NATIVE(glGetBooleanv, "glGetBooleanv", PFNGLGETBOOLEANVPROC);
	GETADDR_NATIVE(glGetDoublev, "glGetDoublev", PFNGLGETDOUBLEVPROC);
	GETADDR_NATIVE(glGetError, "glGetError", PFNGLGETERRORPROC);
	GETADDR_NATIVE(glGetFloatv, "glGetFloatv", PFNGLGETFLOATVPROC);
	GETADDR_NATIVE(glGetIntegerv, "glGetIntegerv", PFNGLGETINTEGERVPROC);
	GETADDR_NATIVE(glGetString, "glGetString", PFNGLGETSTRINGPROC);
	GETADDR_NATIVE(glGetTexImage, "glGetTexImage", PFNGLGETTEXIMAGEPROC);
	GETADDR_NATIVE(glGetTexParameterfv, "glGetTexParameterfv", PFNGLGETTEXPARAMETERFVPROC);
	GETADDR_NATIVE(glGetTexParameteriv, "glGetTexParameteriv", PFNGLGETTEXPARAMETERIVPROC);
	GETADDR_NATIVE(glGetTexLevelParameterfv, "glGetTexLevelParameterfv", PFNGLGETTEXLEVELPARAMETERFVPROC);
	GETADDR_NATIVE(glGetTexLevelParameteriv, "glGetTexLevelParameteriv", PFNGLGETTEXLEVELPARAMETERIVPROC);
	GETADDR_NATIVE(glIsEnabled, "glIsEnabled", PFNGLISENABLEDPROC);
	GETADDR_NATIVE(glDepthRange, "glDepthRange", PFNGLDEPTHRANGEPROC);
	GETADDR_NATIVE(glViewport, "glViewport", PFNGLVIEWPORTPROC);
	#endif

	#ifdef GL_VERSION_1_1
	GETADDR_NATIVE(glDrawArrays, "glDrawArrays", PFNGLDRAWARRAYSPROC);
	GETADDR_NATIVE(glDrawElements, "glDrawElements", PFNGLDRAWELEMENTSPROC);
	GETADDR_NATIVE(glGetPointerv, "glGetPointerv", PFNGLGETPOINTERVPROC);
	GETADDR_NATIVE(glPolygonOffset, "glPolygonOffset", PFNGLPOLYGONOFFSETPROC);
	GETADDR_NATIVE(glCopyTexImage1D, "glCopyTexImage1D", PFNGLCOPYTEXIMAGE1DPROC);
	GETADDR_NATIVE(glCopyTexImage2D, "glCopyTexImage2D", PFNGLCOPYTEXIMAGE2DPROC);
	GETADDR_NATIVE(glCopyTexSubImage1D, "glCopyTexSubImage1D", PFNGLCOPYTEXSUBIMAGE1DPROC);
	GETADDR_NATIVE(glCopyTexSubImage2D, "glCopyTexSubImage2D", PFNGLCOPYTEXSUBIMAGE2DPROC);
	GETADDR_NATIVE(glTexSubImage1D, "glTexSubImage1D", PFNGLTEXSUBIMAGE1DPROC);
	GETADDR_NATIVE(glTexSubImage2D, "glTexSubImage2D", PFNGLTEXSUBIMAGE2DPROC);
	GETADDR_NATIVE(glBindTexture, "glBindTexture", PFNGLBINDTEXTUREPROC);
	GETADDR_NATIVE(glDeleteTextures, "glDeleteTextures", PFNGLDELETETEXTURESPROC);
	GETADDR_NATIVE(glGenTextures, "glGenTextures", PFNGLGENTEXTURESPROC);
	GETADDR_NATIVE(glIsTexture, "glIsTexture", PFNGLISTEXTUREPROC);
	#endif

	#ifdef GL_VERSION_1_2
	GETADDR_BASE(glBlendColor, "glBlendColor", PFNGLBLENDCOLORPROC);
	GETADDR_BASE(glBlendEquation, "glBlendEquation", PFNGLBLENDEQUATIONPROC);
	GETADDR_BASE(glDrawRangeElements, "glDrawRangeElements", PFNGLDRAWRANGEELEMENTSPROC);
	GETADDR_BASE(glTexImage3D, "glTexImage3D", PFNGLTEXIMAGE3DPROC);
	GETADDR_BASE(glTexSubImage3D, "glTexSubImage3D", PFNGLTEXSUBIMAGE3DPROC);
	GETADDR_BASE(glCopyTexSubImage3D, "glCopyTexSubImage3D", PFNGLCOPYTEXSUBIMAGE3DPROC);
	#endif

	#ifdef GL_VERSION_1_3
	GETADDR_BASE(glActiveTexture, "glActiveTexture", PFNGLACTIVETEXTUREPROC);
	GETADDR_BASE(glSampleCoverage, "glSampleCoverage", PFNGLSAMPLECOVERAGEPROC);
	GETADDR_BASE(glCompressedTexImage3D, "glCompressedTexImage3D", PFNGLCOMPRESSEDTEXIMAGE3DPROC);
	GETADDR_BASE(glCompressedTexImage2D, "glCompressedTexImage2D", PFNGLCOMPRESSEDTEXIMAGE2DPROC);
	GETADDR_BASE(glCompressedTexImage1D, "glCompressedTexImage1D", PFNGLCOMPRESSEDTEXIMAGE1DPROC);
	GETADDR_BASE(glCompressedTexSubImage3D, "glCompressedTexSubImage3D", PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC);
	GETADDR_BASE(glCompressedTexSubImage2D, "glCompressedTexSubImage2D", PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC);
	GETADDR_BASE(glCompressedTexSubImage1D, "glCompressedTexSubImage1D", PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC);
	GETADDR_BASE(glGetCompressedTexImage, "glGetCompressedTexImage", PFNGLGETCOMPRESSEDTEXIMAGEPROC);
	#endif

	#ifdef GL_VERSION_1_4
	GETADDR_BASE(glBlendFuncSeparate, "glBlendFuncSeparate", PFNGLBLENDFUNCSEPARATEPROC);
	GETADDR_BASE(glMultiDrawArrays, "glMultiDrawArrays", PFNGLMULTIDRAWARRAYSPROC);
	GETADDR_BASE(glMultiDrawElements, "glMultiDrawElements", PFNGLMULTIDRAWELEMENTSPROC);
	GETADDR_BASE(glPointParameterf, "glPointParameterf", PFNGLPOINTPARAMETERFPROC);
	GETADDR_BASE(glPointParameterfv, "glPointParameterfv", PFNGLPOINTPARAMETERFVPROC);
	GETADDR_BASE(glPointParameteri, "glPointParameteri", PFNGLPOINTPARAMETERIPROC);
	GETADDR_BASE(glPointParameteriv, "glPointParameteriv", PFNGLPOINTPARAMETERIVPROC);
	#endif

	#ifdef GL_VERSION_1_5
	GETADDR_BASE(glGenQueries, "glGenQueries", PFNGLGENQUERIESPROC);
	GETADDR_BASE(glDeleteQueries, "glDeleteQueries", PFNGLDELETEQUERIESPROC);
	GETADDR_BASE(glIsQuery, "glIsQuery", PFNGLISQUERYPROC);
	GETADDR_BASE(glBeginQuery, "glBeginQuery", PFNGLBEGINQUERYPROC);
	GETADDR_BASE(glEndQuery, "glEndQuery", PFNGLENDQUERYPROC);
	GETADDR_BASE(glGetQueryiv, "glGetQueryiv", PFNGLGETQUERYIVPROC);
	GETADDR_BASE(glGetQueryObjectiv, "glGetQueryObjectiv", PFNGLGETQUERYOBJECTIVPROC);
	GETADDR_BASE(glGetQueryObjectuiv, "glGetQueryObjectuiv", PFNGLGETQUERYOBJECTUIVPROC);
	GETADDR_BASE(glBindBuffer, "glBindBuffer", PFNGLBINDBUFFERPROC);
	GETADDR_BASE(glDeleteBuffers, "glDeleteBuffers", PFNGLDELETEBUFFERSPROC);
	GETADDR_BASE(glGenBuffers, "glGenBuffers", PFNGLGENBUFFERSPROC);
	GETADDR_BASE(glIsBuffer, "glIsBuffer", PFNGLISBUFFERPROC);
	GETADDR_BASE(glBufferData, "glBufferData", PFNGLBUFFERDATAPROC);
	GETADDR_BASE(glBufferSubData, "glBufferSubData", PFNGLBUFFERSUBDATAPROC);
	GETADDR_BASE(glGetBufferSubData, "glGetBufferSubData", PFNGLGETBUFFERSUBDATAPROC);
	GETADDR_BASE(glMapBuffer, "glMapBuffer", PFNGLMAPBUFFERPROC);
	GETADDR_BASE(glUnmapBuffer, "glUnmapBuffer", PFNGLUNMAPBUFFERPROC);
	GETADDR_BASE(glGetBufferParameteriv, "glGetBufferParameteriv", PFNGLGETBUFFERPARAMETERIVPROC);
	GETADDR_BASE(glGetBufferPointerv, "glGetBufferPointerv", PFNGLGETBUFFERPOINTERVPROC);
	#endif

	#ifdef GL_VERSION_2_0
	GETADDR_BASE(glBlendEquationSeparate, "glBlendEquationSeparate", PFNGLBLENDEQUATIONSEPARATEPROC);
	GETADDR_BASE(glDrawBuffers, "glDrawBuffers", PFNGLDRAWBUFFERSPROC);
	GETADDR_BASE(glStencilOpSeparate, "glStencilOpSeparate", PFNGLSTENCILOPSEPARATEPROC);
	GETADDR_BASE(glStencilFuncSeparate, "glStencilFuncSeparate", PFNGLSTENCILFUNCSEPARATEPROC);
	GETADDR_BASE(glStencilMaskSeparate, "glStencilMaskSeparate", PFNGLSTENCILMASKSEPARATEPROC);
	GETADDR_BASE(glAttachShader, "glAttachShader", PFNGLATTACHSHADERPROC);
	GETADDR_BASE(glBindAttribLocation, "glBindAttribLocation", PFNGLBINDATTRIBLOCATIONPROC);
	GETADDR_BASE(glCompileShader, "glCompileShader", PFNGLCOMPILESHADERPROC);
	GETADDR_BASE(glCreateProgram, "glCreateProgram", PFNGLCREATEPROGRAMPROC);
	GETADDR_BASE(glCreateShader, "glCreateShader", PFNGLCREATESHADERPROC);
	GETADDR_BASE(glDeleteProgram, "glDeleteProgram", PFNGLDELETEPROGRAMPROC);
	GETADDR_BASE(glDeleteShader, "glDeleteShader", PFNGLDELETESHADERPROC);
	GETADDR_BASE(glDetachShader, "glDetachShader", PFNGLDETACHSHADERPROC);
	GETADDR_BASE(glDisableVertexAttribArray, "glDisableVertexAttribArray", PFNGLDISABLEVERTEXATTRIBARRAYPROC);
	GETADDR_BASE(glEnableVertexAttribArray, "glEnableVertexAttribArray", PFNGLENABLEVERTEXATTRIBARRAYPROC);
	GETADDR_BASE(glGetActiveAttrib, "glGetActiveAttrib", PFNGLGETACTIVEATTRIBPROC);
	GETADDR_BASE(glGetActiveUniform, "glGetActiveUniform", PFNGLGETACTIVEUNIFORMPROC);
	GETADDR_BASE(glGetAttachedShaders, "glGetAttachedShaders", PFNGLGETATTACHEDSHADERSPROC);
	GETADDR_BASE(glGetAttribLocation, "glGetAttribLocation", PFNGLGETATTRIBLOCATIONPROC);
	GETADDR_BASE(glGetProgramiv, "glGetProgramiv", PFNGLGETPROGRAMIVPROC);
	GETADDR_BASE(glGetProgramInfoLog, "glGetProgramInfoLog", PFNGLGETPROGRAMINFOLOGPROC);
	GETADDR_BASE(glGetShaderiv, "glGetShaderiv", PFNGLGETSHADERIVPROC);
	GETADDR_BASE(glGetShaderInfoLog, "glGetShaderInfoLog", PFNGLGETSHADERINFOLOGPROC);
	GETADDR_BASE(glGetShaderSource, "glGetShaderSource", PFNGLGETSHADERSOURCEPROC);
	GETADDR_BASE(glGetUniformLocation, "glGetUniformLocation", PFNGLGETUNIFORMLOCATIONPROC);
	GETADDR_BASE(glGetUniformfv, "glGetUniformfv", PFNGLGETUNIFORMFVPROC);
	GETADDR_BASE(glGetUniformiv, "glGetUniformiv", PFNGLGETUNIFORMIVPROC);
	GETADDR_BASE(glGetVertexAttribdv, "glGetVertexAttribdv", PFNGLGETVERTEXATTRIBDVPROC);
	GETADDR_BASE(glGetVertexAttribfv, "glGetVertexAttribfv", PFNGLGETVERTEXATTRIBFVPROC);
	GETADDR_BASE(glGetVertexAttribiv, "glGetVertexAttribiv", PFNGLGETVERTEXATTRIBIVPROC);
	GETADDR_BASE(glGetVertexAttribPointerv, "glGetVertexAttribPointerv", PFNGLGETVERTEXATTRIBPOINTERVPROC);
	GETADDR_BASE(glIsProgram, "glIsProgram", PFNGLISPROGRAMPROC);
	GETADDR_BASE(glIsShader, "glIsShader", PFNGLISSHADERPROC);
	GETADDR_BASE(glLinkProgram, "glLinkProgram", PFNGLLINKPROGRAMPROC);
	GETADDR_BASE(glShaderSource, "glShaderSource", PFNGLSHADERSOURCEPROC);
	GETADDR_BASE(glUseProgram, "glUseProgram", PFNGLUSEPROGRAMPROC);
	GETADDR_BASE(glUniform1f, "glUniform1f", PFNGLUNIFORM1FPROC);
	GETADDR_BASE(glUniform2f, "glUniform2f", PFNGLUNIFORM2FPROC);
	GETADDR_BASE(glUniform3f, "glUniform3f", PFNGLUNIFORM3FPROC);
	GETADDR_BASE(glUniform4f, "glUniform4f", PFNGLUNIFORM4FPROC);
	GETADDR_BASE(glUniform1i, "glUniform1i", PFNGLUNIFORM1IPROC);
	GETADDR_BASE(glUniform2i, "glUniform2i", PFNGLUNIFORM2IPROC);
	GETADDR_BASE(glUniform3i, "glUniform3i", PFNGLUNIFORM3IPROC);
	GETADDR_BASE(glUniform4i, "glUniform4i", PFNGLUNIFORM4IPROC);
	GETADDR_BASE(glUniform1fv, "glUniform1fv", PFNGLUNIFORM1FVPROC);
	GETADDR_BASE(glUniform2fv, "glUniform2fv", PFNGLUNIFORM2FVPROC);
	GETADDR_BASE(glUniform3fv, "glUniform3fv", PFNGLUNIFORM3FVPROC);
	GETADDR_BASE(glUniform4fv, "glUniform4fv", PFNGLUNIFORM4FVPROC);
	GETADDR_BASE(glUniform1iv, "glUniform1iv", PFNGLUNIFORM1IVPROC);
	GETADDR_BASE(glUniform2iv, "glUniform2iv", PFNGLUNIFORM2IVPROC);
	GETADDR_BASE(glUniform3iv, "glUniform3iv", PFNGLUNIFORM3IVPROC);
	GETADDR_BASE(glUniform4iv, "glUniform4iv", PFNGLUNIFORM4IVPROC);
	GETADDR_BASE(glUniformMatrix2fv, "glUniformMatrix2fv", PFNGLUNIFORMMATRIX2FVPROC);
	GETADDR_BASE(glUniformMatrix3fv, "glUniformMatrix3fv", PFNGLUNIFORMMATRIX3FVPROC);
	GETADDR_BASE(glUniformMatrix4fv, "glUniformMatrix4fv", PFNGLUNIFORMMATRIX4FVPROC);
	GETADDR_BASE(glValidateProgram, "glValidateProgram", PFNGLVALIDATEPROGRAMPROC);
	GETADDR_BASE(glVertexAttrib1d, "glVertexAttrib1d", PFNGLVERTEXATTRIB1DPROC);
	GETADDR_BASE(glVertexAttrib1dv, "glVertexAttrib1dv", PFNGLVERTEXATTRIB1DVPROC);
	GETADDR_BASE(glVertexAttrib1f, "glVertexAttrib1f", PFNGLVERTEXATTRIB1FPROC);
	GETADDR_BASE(glVertexAttrib1fv, "glVertexAttrib1fv", PFNGLVERTEXATTRIB1FVPROC);
	GETADDR_BASE(glVertexAttrib1s, "glVertexAttrib1s", PFNGLVERTEXATTRIB1SPROC);
	GETADDR_BASE(glVertexAttrib1sv, "glVertexAttrib1sv", PFNGLVERTEXATTRIB1SVPROC);
	GETADDR_BASE(glVertexAttrib2d, "glVertexAttrib2d", PFNGLVERTEXATTRIB2DPROC);
	GETADDR_BASE(glVertexAttrib2dv, "glVertexAttrib2dv", PFNGLVERTEXATTRIB2DVPROC);
	GETADDR_BASE(glVertexAttrib2f, "glVertexAttrib2f", PFNGLVERTEXATTRIB2FPROC);
	GETADDR_BASE(glVertexAttrib2fv, "glVertexAttrib2fv", PFNGLVERTEXATTRIB2FVPROC);
	GETADDR_BASE(glVertexAttrib2s, "glVertexAttrib2s", PFNGLVERTEXATTRIB2SPROC);
	GETADDR_BASE(glVertexAttrib2sv, "glVertexAttrib2sv", PFNGLVERTEXATTRIB2SVPROC);
	GETADDR_BASE(glVertexAttrib3d, "glVertexAttrib3d", PFNGLVERTEXATTRIB3DPROC);
	GETADDR_BASE(glVertexAttrib3dv, "glVertexAttrib3dv", PFNGLVERTEXATTRIB3DVPROC);
	GETADDR_BASE(glVertexAttrib3f, "glVertexAttrib3f", PFNGLVERTEXATTRIB3FPROC);
	GETADDR_BASE(glVertexAttrib3fv, "glVertexAttrib3fv", PFNGLVERTEXATTRIB3FVPROC);
	GETADDR_BASE(glVertexAttrib3s, "glVertexAttrib3s", PFNGLVERTEXATTRIB3SPROC);
	GETADDR_BASE(glVertexAttrib3sv, "glVertexAttrib3sv", PFNGLVERTEXATTRIB3SVPROC);
	GETADDR_BASE(glVertexAttrib4Nbv, "glVertexAttrib4Nbv", PFNGLVERTEXATTRIB4NBVPROC);
	GETADDR_BASE(glVertexAttrib4Niv, "glVertexAttrib4Niv", PFNGLVERTEXATTRIB4NIVPROC);
	GETADDR_BASE(glVertexAttrib4Nsv, "glVertexAttrib4Nsv", PFNGLVERTEXATTRIB4NSVPROC);
	GETADDR_BASE(glVertexAttrib4Nub, "glVertexAttrib4Nub", PFNGLVERTEXATTRIB4NUBPROC);
	GETADDR_BASE(glVertexAttrib4Nubv, "glVertexAttrib4Nubv", PFNGLVERTEXATTRIB4NUBVPROC);
	GETADDR_BASE(glVertexAttrib4Nuiv, "glVertexAttrib4Nuiv", PFNGLVERTEXATTRIB4NUIVPROC);
	GETADDR_BASE(glVertexAttrib4Nusv, "glVertexAttrib4Nusv", PFNGLVERTEXATTRIB4NUSVPROC);
	GETADDR_BASE(glVertexAttrib4bv, "glVertexAttrib4bv", PFNGLVERTEXATTRIB4BVPROC);
	GETADDR_BASE(glVertexAttrib4d, "glVertexAttrib4d", PFNGLVERTEXATTRIB4DPROC);
	GETADDR_BASE(glVertexAttrib4dv, "glVertexAttrib4dv", PFNGLVERTEXATTRIB4DVPROC);
	GETADDR_BASE(glVertexAttrib4f, "glVertexAttrib4f", PFNGLVERTEXATTRIB4FPROC);
	GETADDR_BASE(glVertexAttrib4fv, "glVertexAttrib4fv", PFNGLVERTEXATTRIB4FVPROC);
	GETADDR_BASE(glVertexAttrib4iv, "glVertexAttrib4iv", PFNGLVERTEXATTRIB4IVPROC);
	GETADDR_BASE(glVertexAttrib4s, "glVertexAttrib4s", PFNGLVERTEXATTRIB4SPROC);
	GETADDR_BASE(glVertexAttrib4sv, "glVertexAttrib4sv", PFNGLVERTEXATTRIB4SVPROC);
	GETADDR_BASE(glVertexAttrib4ubv, "glVertexAttrib4ubv", PFNGLVERTEXATTRIB4UBVPROC);
	GETADDR_BASE(glVertexAttrib4uiv, "glVertexAttrib4uiv", PFNGLVERTEXATTRIB4UIVPROC);
	GETADDR_BASE(glVertexAttrib4usv, "glVertexAttrib4usv", PFNGLVERTEXATTRIB4USVPROC);
	GETADDR_BASE(glVertexAttribPointer, "glVertexAttribPointer", PFNGLVERTEXATTRIBPOINTERPROC);
	#endif

	#ifdef GL_VERSION_2_1
	GETADDR_BASE(glUniformMatrix2x3fv, "glUniformMatrix2x3fv", PFNGLUNIFORMMATRIX2X3FVPROC);
	GETADDR_BASE(glUniformMatrix3x2fv, "glUniformMatrix3x2fv", PFNGLUNIFORMMATRIX3X2FVPROC);
	GETADDR_BASE(glUniformMatrix2x4fv, "glUniformMatrix2x4fv", PFNGLUNIFORMMATRIX2X4FVPROC);
	GETADDR_BASE(glUniformMatrix4x2fv, "glUniformMatrix4x2fv", PFNGLUNIFORMMATRIX4X2FVPROC);
	GETADDR_BASE(glUniformMatrix3x4fv, "glUniformMatrix3x4fv", PFNGLUNIFORMMATRIX3X4FVPROC);
	GETADDR_BASE(glUniformMatrix4x3fv, "glUniformMatrix4x3fv", PFNGLUNIFORMMATRIX4X3FVPROC);
	#endif

	#ifdef GL_VERSION_3_0
	GETADDR_BASE(glColorMaski, "glColorMaski", PFNGLCOLORMASKIPROC);
	GETADDR_BASE(glGetBooleani_v, "glGetBooleani_v", PFNGLGETBOOLEANI_VPROC);
	GETADDR_BASE(glGetIntegeri_v, "glGetIntegeri_v", PFNGLGETINTEGERI_VPROC);
	GETADDR_BASE(glEnablei, "glEnablei", PFNGLENABLEIPROC);
	GETADDR_BASE(glDisablei, "glDisablei", PFNGLDISABLEIPROC);
	GETADDR_BASE(glIsEnabledi, "glIsEnabledi", PFNGLISENABLEDIPROC);
	GETADDR_BASE(glBeginTransformFeedback, "glBeginTransformFeedback", PFNGLBEGINTRANSFORMFEEDBACKPROC);
	GETADDR_BASE(glEndTransformFeedback, "glEndTransformFeedback", PFNGLENDTRANSFORMFEEDBACKPROC);
	GETADDR_BASE(glBindBufferRange, "glBindBufferRange", PFNGLBINDBUFFERRANGEPROC);
	GETADDR_BASE(glBindBufferBase, "glBindBufferBase", PFNGLBINDBUFFERBASEPROC);
	GETADDR_BASE(glTransformFeedbackVaryings, "glTransformFeedbackVaryings", PFNGLTRANSFORMFEEDBACKVARYINGSPROC);
	GETADDR_BASE(glGetTransformFeedbackVarying, "glGetTransformFeedbackVarying", PFNGLGETTRANSFORMFEEDBACKVARYINGPROC);
	GETADDR_BASE(glClampColor, "glClampColor", PFNGLCLAMPCOLORPROC);
	GETADDR_BASE(glBeginConditionalRender, "glBeginConditionalRender", PFNGLBEGINCONDITIONALRENDERPROC);
	GETADDR_BASE(glEndConditionalRender, "glEndConditionalRender", PFNGLENDCONDITIONALRENDERPROC);
	GETADDR_BASE(glVertexAttribIPointer, "glVertexAttribIPointer", PFNGLVERTEXATTRIBIPOINTERPROC);
	GETADDR_BASE(glGetVertexAttribIiv, "glGetVertexAttribIiv", PFNGLGETVERTEXATTRIBIIVPROC);
	GETADDR_BASE(glGetVertexAttribIuiv, "glGetVertexAttribIuiv", PFNGLGETVERTEXATTRIBIUIVPROC);
	GETADDR_BASE(glVertexAttribI1i, "glVertexAttribI1i", PFNGLVERTEXATTRIBI1IPROC);
	GETADDR_BASE(glVertexAttribI2i, "glVertexAttribI2i", PFNGLVERTEXATTRIBI2IPROC);
	GETADDR_BASE(glVertexAttribI3i, "glVertexAttribI3i", PFNGLVERTEXATTRIBI3IPROC);
	GETADDR_BASE(glVertexAttribI4i, "glVertexAttribI4i", PFNGLVERTEXATTRIBI4IPROC);
	GETADDR_BASE(glVertexAttribI1ui, "glVertexAttribI1ui", PFNGLVERTEXATTRIBI1UIPROC);
	GETADDR_BASE(glVertexAttribI2ui, "glVertexAttribI2ui", PFNGLVERTEXATTRIBI2UIPROC);
	GETADDR_BASE(glVertexAttribI3ui, "glVertexAttribI3ui", PFNGLVERTEXATTRIBI3UIPROC);
	GETADDR_BASE(glVertexAttribI4ui, "glVertexAttribI4ui", PFNGLVERTEXATTRIBI4UIPROC);
	GETADDR_BASE(glVertexAttribI1iv, "glVertexAttribI1iv", PFNGLVERTEXATTRIBI1IVPROC);
	GETADDR_BASE(glVertexAttribI2iv, "glVertexAttribI2iv", PFNGLVERTEXATTRIBI2IVPROC);
	GETADDR_BASE(glVertexAttribI3iv, "glVertexAttribI3iv", PFNGLVERTEXATTRIBI3IVPROC);
	GETADDR_BASE(glVertexAttribI4iv, "glVertexAttribI4iv", PFNGLVERTEXATTRIBI4IVPROC);
	GETADDR_BASE(glVertexAttribI1uiv, "glVertexAttribI1uiv", PFNGLVERTEXATTRIBI1UIVPROC);
	GETADDR_BASE(glVertexAttribI2uiv, "glVertexAttribI2uiv", PFNGLVERTEXATTRIBI2UIVPROC);
	GETADDR_BASE(glVertexAttribI3uiv, "glVertexAttribI3uiv", PFNGLVERTEXATTRIBI3UIVPROC);
	GETADDR_BASE(glVertexAttribI4uiv, "glVertexAttribI4uiv", PFNGLVERTEXATTRIBI4UIVPROC);
	GETADDR_BASE(glVertexAttribI4bv, "glVertexAttribI4bv", PFNGLVERTEXATTRIBI4BVPROC);
	GETADDR_BASE(glVertexAttribI4sv, "glVertexAttribI4sv", PFNGLVERTEXATTRIBI4SVPROC);
	GETADDR_BASE(glVertexAttribI4ubv, "glVertexAttribI4ubv", PFNGLVERTEXATTRIBI4UBVPROC);
	GETADDR_BASE(glVertexAttribI4usv, "glVertexAttribI4usv", PFNGLVERTEXATTRIBI4USVPROC);
	GETADDR_BASE(glGetUniformuiv, "glGetUniformuiv", PFNGLGETUNIFORMUIVPROC);
	GETADDR_BASE(glBindFragDataLocation, "glBindFragDataLocation", PFNGLBINDFRAGDATALOCATIONPROC);
	GETADDR_BASE(glGetFragDataLocation, "glGetFragDataLocation", PFNGLGETFRAGDATALOCATIONPROC);
	GETADDR_BASE(glUniform1ui, "glUniform1ui", PFNGLUNIFORM1UIPROC);
	GETADDR_BASE(glUniform2ui, "glUniform2ui", PFNGLUNIFORM2UIPROC);
	GETADDR_BASE(glUniform3ui, "glUniform3ui", PFNGLUNIFORM3UIPROC);
	GETADDR_BASE(glUniform4ui, "glUniform4ui", PFNGLUNIFORM4UIPROC);
	GETADDR_BASE(glUniform1uiv, "glUniform1uiv", PFNGLUNIFORM1UIVPROC);
	GETADDR_BASE(glUniform2uiv, "glUniform2uiv", PFNGLUNIFORM2UIVPROC);
	GETADDR_BASE(glUniform3uiv, "glUniform3uiv", PFNGLUNIFORM3UIVPROC);
	GETADDR_BASE(glUniform4uiv, "glUniform4uiv", PFNGLUNIFORM4UIVPROC);
	GETADDR_BASE(glTexParameterIiv, "glTexParameterIiv", PFNGLTEXPARAMETERIIVPROC);
	GETADDR_BASE(glTexParameterIuiv, "glTexParameterIuiv", PFNGLTEXPARAMETERIUIVPROC);
	GETADDR_BASE(glGetTexParameterIiv, "glGetTexParameterIiv", PFNGLGETTEXPARAMETERIIVPROC);
	GETADDR_BASE(glGetTexParameterIuiv, "glGetTexParameterIuiv", PFNGLGETTEXPARAMETERIUIVPROC);
	GETADDR_BASE(glClearBufferiv, "glClearBufferiv", PFNGLCLEARBUFFERIVPROC);
	GETADDR_BASE(glClearBufferuiv, "glClearBufferuiv", PFNGLCLEARBUFFERUIVPROC);
	GETADDR_BASE(glClearBufferfv, "glClearBufferfv", PFNGLCLEARBUFFERFVPROC);
	GETADDR_BASE(glClearBufferfi, "glClearBufferfi", PFNGLCLEARBUFFERFIPROC);
	GETADDR_BASE(glGetStringi, "glGetStringi", PFNGLGETSTRINGIPROC);
	#endif

	#ifdef GL_VERSION_3_1
	GETADDR_BASE(glDrawArraysInstanced, "glDrawArraysInstanced", PFNGLDRAWARRAYSINSTANCEDPROC);
	GETADDR_BASE(glDrawElementsInstanced, "glDrawElementsInstanced", PFNGLDRAWELEMENTSINSTANCEDPROC);
	GETADDR_BASE(glTexBuffer, "glTexBuffer", PFNGLTEXBUFFERPROC);
	GETADDR_BASE(glPrimitiveRestartIndex, "glPrimitiveRestartIndex", PFNGLPRIMITIVERESTARTINDEXPROC);
	#endif

	#ifdef GL_VERSION_3_2
	GETADDR_BASE(glGetInteger64i_v, "glGetInteger64i_v", PFNGLGETINTEGER64I_VPROC);
	GETADDR_BASE(glGetBufferParameteri64v, "glGetBufferParameteri64v", PFNGLGETBUFFERPARAMETERI64VPROC);
	GETADDR_BASE(glFramebufferTexture, "glFramebufferTexture", PFNGLFRAMEBUFFERTEXTUREPROC);
	#endif

	#ifdef GL_VERSION_3_3
	GETADDR_BASE(glVertexAttribDivisor, "glVertexAttribDivisor", PFNGLVERTEXATTRIBDIVISORPROC);
	#endif

	#ifdef GL_ARB_framebuffer_object
	GETADDR_BASE(glIsRenderbuffer, "glIsRenderbuffer", PFNGLISRENDERBUFFERPROC);
	GETADDR_BASE(glBindRenderbuffer, "glBindRenderbuffer", PFNGLBINDRENDERBUFFERPROC);
	GETADDR_BASE(glDeleteRenderbuffers, "glDeleteRenderbuffers", PFNGLDELETERENDERBUFFERSPROC);
	GETADDR_BASE(glGenRenderbuffers, "glGenRenderbuffers", PFNGLGENRENDERBUFFERSPROC);
	GETADDR_BASE(glRenderbufferStorage, "glRenderbufferStorage", PFNGLRENDERBUFFERSTORAGEPROC);
	GETADDR_BASE(glGetRenderbufferParameteriv, "glGetRenderbufferParameteriv", PFNGLGETRENDERBUFFERPARAMETERIVPROC);
	GETADDR_BASE(glIsFramebuffer, "glIsFramebuffer", PFNGLISFRAMEBUFFERPROC);
	GETADDR_BASE(glBindFramebuffer, "glBindFramebuffer", PFNGLBINDFRAMEBUFFERPROC);
	GETADDR_BASE(glDeleteFramebuffers, "glDeleteFramebuffers", PFNGLDELETEFRAMEBUFFERSPROC);
	GETADDR_BASE(glGenFramebuffers, "glGenFramebuffers", PFNGLGENFRAMEBUFFERSPROC);
	GETADDR_BASE(glCheckFramebufferStatus, "glCheckFramebufferStatus", PFNGLCHECKFRAMEBUFFERSTATUSPROC);
	GETADDR_BASE(glFramebufferTexture1D, "glFramebufferTexture1D", PFNGLFRAMEBUFFERTEXTURE1DPROC);
	GETADDR_BASE(glFramebufferTexture2D, "glFramebufferTexture2D", PFNGLFRAMEBUFFERTEXTURE2DPROC);
	GETADDR_BASE(glFramebufferTexture3D, "glFramebufferTexture3D", PFNGLFRAMEBUFFERTEXTURE3DPROC);
	GETADDR_BASE(glFramebufferRenderbuffer, "glFramebufferRenderbuffer", PFNGLFRAMEBUFFERRENDERBUFFERPROC);
	GETADDR_BASE(glGetFramebufferAttachmentParameteriv, "glGetFramebufferAttachmentParameteriv", PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC);
	GETADDR_BASE(glGenerateMipmap, "glGenerateMipmap", PFNGLGENERATEMIPMAPPROC);
	GETADDR_BASE(glBlitFramebuffer, "glBlitFramebuffer", PFNGLBLITFRAMEBUFFERPROC);
	GETADDR_BASE(glRenderbufferStorageMultisample, "glRenderbufferStorageMultisample", PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC);
	GETADDR_BASE(glFramebufferTextureLayer, "glFramebufferTextureLayer", PFNGLFRAMEBUFFERTEXTURELAYERPROC);
	#endif

	#ifdef GL_ARB_map_buffer_range
	GETADDR_BASE(glMapBufferRange, "glMapBufferRange", PFNGLMAPBUFFERRANGEPROC);
	GETADDR_BASE(glFlushMappedBufferRange, "glFlushMappedBufferRange", PFNGLFLUSHMAPPEDBUFFERRANGEPROC);
	#endif

	#ifdef GL_ARB_vertex_array_object
	GETADDR_BASE(glBindVertexArray, "glBindVertexArray", PFNGLBINDVERTEXARRAYPROC);
	GETADDR_BASE(glDeleteVertexArrays, "glDeleteVertexArrays", PFNGLDELETEVERTEXARRAYSPROC);
	GETADDR_BASE(glGenVertexArrays, "glGenVertexArrays", PFNGLGENVERTEXARRAYSPROC);
	GETADDR_BASE(glIsVertexArray, "glIsVertexArray", PFNGLISVERTEXARRAYPROC);
	#endif

	#ifdef GL_ARB_uniform_buffer_object
	GETADDR_BASE(glGetUniformIndices, "glGetUniformIndices", PFNGLGETUNIFORMINDICESPROC);
	GETADDR_BASE(glGetActiveUniformsiv, "glGetActiveUniformsiv", PFNGLGETACTIVEUNIFORMSIVPROC);
	GETADDR_BASE(glGetActiveUniformName, "glGetActiveUniformName", PFNGLGETACTIVEUNIFORMNAMEPROC);
	GETADDR_BASE(glGetUniformBlockIndex, "glGetUniformBlockIndex", PFNGLGETUNIFORMBLOCKINDEXPROC);
	GETADDR_BASE(glGetActiveUniformBlockiv, "glGetActiveUniformBlockiv", PFNGLGETACTIVEUNIFORMBLOCKIVPROC);
	GETADDR_BASE(glGetActiveUniformBlockName, "glGetActiveUniformBlockName", PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC);
	GETADDR_BASE(glUniformBlockBinding, "glUniformBlockBinding", PFNGLUNIFORMBLOCKBINDINGPROC);
	#endif

	#ifdef GL_ARB_copy_buffer
	GETADDR_BASE(glCopyBufferSubData, "glCopyBufferSubData", PFNGLCOPYBUFFERSUBDATAPROC);
	#endif

	#ifdef GL_ARB_draw_elements_base_vertex
	GETADDR_BASE(glDrawElementsBaseVertex, "glDrawElementsBaseVertex", PFNGLDRAWELEMENTSBASEVERTEXPROC);
	GETADDR_BASE(glDrawRangeElementsBaseVertex, "glDrawRangeElementsBaseVertex", PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC);
	GETADDR_BASE(glDrawElementsInstancedBaseVertex, "glDrawElementsInstancedBaseVertex", PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC);
	GETADDR_BASE(glMultiDrawElementsBaseVertex, "glMultiDrawElementsBaseVertex", PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC);
	#endif

	#ifdef GL_ARB_provoking_vertex
	GETADDR_BASE(glProvokingVertex, "glProvokingVertex", PFNGLPROVOKINGVERTEXPROC);
	#endif

	#ifdef GL_ARB_sync
	GETADDR_BASE(glFenceSync, "glFenceSync", PFNGLFENCESYNCPROC);
	GETADDR_BASE(glIsSync, "glIsSync", PFNGLISSYNCPROC);
	GETADDR_BASE(glDeleteSync, "glDeleteSync", PFNGLDELETESYNCPROC);
	GETADDR_BASE(glClientWaitSync, "glClientWaitSync", PFNGLCLIENTWAITSYNCPROC);
	GETADDR_BASE(glWaitSync, "glWaitSync", PFNGLWAITSYNCPROC);
	GETADDR_BASE(glGetInteger64v, "glGetInteger64v", PFNGLGETINTEGER64VPROC);
	GETADDR_BASE(glGetSynciv, "glGetSynciv", PFNGLGETSYNCIVPROC);
	#endif

	#ifdef GL_ARB_texture_multisample
	GETADDR_BASE(glTexImage2DMultisample, "glTexImage2DMultisample", PFNGLTEXIMAGE2DMULTISAMPLEPROC);
	GETADDR_BASE(glTexImage3DMultisample, "glTexImage3DMultisample", PFNGLTEXIMAGE3DMULTISAMPLEPROC);
	GETADDR_BASE(glGetMultisamplefv, "glGetMultisamplefv", PFNGLGETMULTISAMPLEFVPROC);
	GETADDR_BASE(glSampleMaski, "glSampleMaski", PFNGLSAMPLEMASKIPROC);
	#endif

	#ifdef GL_ARB_blend_func_extended
	GETADDR_BASE(glBindFragDataLocationIndexed, "glBindFragDataLocationIndexed", PFNGLBINDFRAGDATALOCATIONINDEXEDPROC);
	GETADDR_BASE(glGetFragDataIndex, "glGetFragDataIndex", PFNGLGETFRAGDATAINDEXPROC);
	#endif

	#ifdef GL_ARB_sampler_objects
	GETADDR_BASE(glGenSamplers, "glGenSamplers", PFNGLGENSAMPLERSPROC);
	GETADDR_BASE(glDeleteSamplers, "glDeleteSamplers", PFNGLDELETESAMPLERSPROC);
	GETADDR_BASE(glIsSampler, "glIsSampler", PFNGLISSAMPLERPROC);
	GETADDR_BASE(glBindSampler, "glBindSampler", PFNGLBINDSAMPLERPROC);
	GETADDR_BASE(glSamplerParameteri, "glSamplerParameteri", PFNGLSAMPLERPARAMETERIPROC);
	GETADDR_BASE(glSamplerParameteriv, "glSamplerParameteriv", PFNGLSAMPLERPARAMETERIVPROC);
	GETADDR_BASE(glSamplerParameterf, "glSamplerParameterf", PFNGLSAMPLERPARAMETERFPROC);
	GETADDR_BASE(glSamplerParameterfv, "glSamplerParameterfv", PFNGLSAMPLERPARAMETERFVPROC);
	GETADDR_BASE(glSamplerParameterIiv, "glSamplerParameterIiv", PFNGLSAMPLERPARAMETERIIVPROC);
	GETADDR_BASE(glSamplerParameterIuiv, "glSamplerParameterIuiv", PFNGLSAMPLERPARAMETERIUIVPROC);
	GETADDR_BASE(glGetSamplerParameteriv, "glGetSamplerParameteriv", PFNGLGETSAMPLERPARAMETERIVPROC);
	GETADDR_BASE(glGetSamplerParameterIiv, "glGetSamplerParameterIiv", PFNGLGETSAMPLERPARAMETERIIVPROC);
	GETADDR_BASE(glGetSamplerParameterfv, "glGetSamplerParameterfv", PFNGLGETSAMPLERPARAMETERFVPROC);
	GETADDR_BASE(glGetSamplerParameterIuiv, "glGetSamplerParameterIuiv", PFNGLGETSAMPLERPARAMETERIUIVPROC);
	#endif

	#ifdef GL_ARB_timer_query
	GETADDR_BASE(glQueryCounter, "glQueryCounter", PFNGLQUERYCOUNTERPROC);
	GETADDR_BASE(glGetQueryObjecti64v, "glGetQueryObjecti64v", PFNGLGETQUERYOBJECTI64VPROC);
	GETADDR_BASE(glGetQueryObjectui64v, "glGetQueryObjectui64v", PFNGLGETQUERYOBJECTUI64VPROC);
	#endif

	#ifdef GL_ARB_vertex_type_2_10_10_10_rev
	GETADDR_BASE(glVertexP2ui, "glVertexP2ui", PFNGLVERTEXP2UIPROC);
	GETADDR_BASE(glVertexP2uiv, "glVertexP2uiv", PFNGLVERTEXP2UIVPROC);
	GETADDR_BASE(glVertexP3ui, "glVertexP3ui", PFNGLVERTEXP3UIPROC);
	GETADDR_BASE(glVertexP3uiv, "glVertexP3uiv", PFNGLVERTEXP3UIVPROC);
	GETADDR_BASE(glVertexP4ui, "glVertexP4ui", PFNGLVERTEXP4UIPROC);
	GETADDR_BASE(glVertexP4uiv, "glVertexP4uiv", PFNGLVERTEXP4UIVPROC);
	GETADDR_BASE(glTexCoordP1ui, "glTexCoordP1ui", PFNGLTEXCOORDP1UIPROC);
	GETADDR_BASE(glTexCoordP1uiv, "glTexCoordP1uiv", PFNGLTEXCOORDP1UIVPROC);
	GETADDR_BASE(glTexCoordP2ui, "glTexCoordP2ui", PFNGLTEXCOORDP2UIPROC);
	GETADDR_BASE(glTexCoordP2uiv, "glTexCoordP2uiv", PFNGLTEXCOORDP2UIVPROC);
	GETADDR_BASE(glTexCoordP3ui, "glTexCoordP3ui", PFNGLTEXCOORDP3UIPROC);
	GETADDR_BASE(glTexCoordP3uiv, "glTexCoordP3uiv", PFNGLTEXCOORDP3UIVPROC);
	GETADDR_BASE(glTexCoordP4ui, "glTexCoordP4ui", PFNGLTEXCOORDP4UIPROC);
	GETADDR_BASE(glTexCoordP4uiv, "glTexCoordP4uiv", PFNGLTEXCOORDP4UIVPROC);
	GETADDR_BASE(glMultiTexCoordP1ui, "glMultiTexCoordP1ui", PFNGLMULTITEXCOORDP1UIPROC);
	GETADDR_BASE(glMultiTexCoordP1uiv, "glMultiTexCoordP1uiv", PFNGLMULTITEXCOORDP1UIVPROC);
	GETADDR_BASE(glMultiTexCoordP2ui, "glMultiTexCoordP2ui", PFNGLMULTITEXCOORDP2UIPROC);
	GETADDR_BASE(glMultiTexCoordP2uiv, "glMultiTexCoordP2uiv", PFNGLMULTITEXCOORDP2UIVPROC);
	GETADDR_BASE(glMultiTexCoordP3ui, "glMultiTexCoordP3ui", PFNGLMULTITEXCOORDP3UIPROC);
	GETADDR_BASE(glMultiTexCoordP3uiv, "glMultiTexCoordP3uiv", PFNGLMULTITEXCOORDP3UIVPROC);
	GETADDR_BASE(glMultiTexCoordP4ui, "glMultiTexCoordP4ui", PFNGLMULTITEXCOORDP4UIPROC);
	GETADDR_BASE(glMultiTexCoordP4uiv, "glMultiTexCoordP4uiv", PFNGLMULTITEXCOORDP4UIVPROC);
	GETADDR_BASE(glNormalP3ui, "glNormalP3ui", PFNGLNORMALP3UIPROC);
	GETADDR_BASE(glNormalP3uiv, "glNormalP3uiv", PFNGLNORMALP3UIVPROC);
	GETADDR_BASE(glColorP3ui, "glColorP3ui", PFNGLCOLORP3UIPROC);
	GETADDR_BASE(glColorP3uiv, "glColorP3uiv", PFNGLCOLORP3UIVPROC);
	GETADDR_BASE(glColorP4ui, "glColorP4ui", PFNGLCOLORP4UIPROC);
	GETADDR_BASE(glColorP4uiv, "glColorP4uiv", PFNGLCOLORP4UIVPROC);
	GETADDR_BASE(glSecondaryColorP3ui, "glSecondaryColorP3ui", PFNGLSECONDARYCOLORP3UIPROC);
	GETADDR_BASE(glSecondaryColorP3uiv, "glSecondaryColorP3uiv", PFNGLSECONDARYCOLORP3UIVPROC);
	GETADDR_BASE(glVertexAttribP1ui, "glVertexAttribP1ui", PFNGLVERTEXATTRIBP1UIPROC);
	GETADDR_BASE(glVertexAttribP1uiv, "glVertexAttribP1uiv", PFNGLVERTEXATTRIBP1UIVPROC);
	GETADDR_BASE(glVertexAttribP2ui, "glVertexAttribP2ui", PFNGLVERTEXATTRIBP2UIPROC);
	GETADDR_BASE(glVertexAttribP2uiv, "glVertexAttribP2uiv", PFNGLVERTEXATTRIBP2UIVPROC);
	GETADDR_BASE(glVertexAttribP3ui, "glVertexAttribP3ui", PFNGLVERTEXATTRIBP3UIPROC);
	GETADDR_BASE(glVertexAttribP3uiv, "glVertexAttribP3uiv", PFNGLVERTEXATTRIBP3UIVPROC);
	GETADDR_BASE(glVertexAttribP4ui, "glVertexAttribP4ui", PFNGLVERTEXATTRIBP4UIPROC);
	GETADDR_BASE(glVertexAttribP4uiv, "glVertexAttribP4uiv", PFNGLVERTEXATTRIBP4UIVPROC);
	#endif

	//chegando aqui carreguei tudo
	return true;
}

namespace HorseRadish
{

namespace OpenGL
{

#ifdef GL_VERSION_1_0
PFNGLCULLFACEPROC glCullFace;
PFNGLFRONTFACEPROC glFrontFace;
PFNGLHINTPROC glHint;
PFNGLLINEWIDTHPROC glLineWidth;
PFNGLPOINTSIZEPROC glPointSize;
PFNGLPOLYGONMODEPROC glPolygonMode;
PFNGLSCISSORPROC glScissor;
PFNGLTEXPARAMETERFPROC glTexParameterf;
PFNGLTEXPARAMETERFVPROC glTexParameterfv;
PFNGLTEXPARAMETERIPROC glTexParameteri;
PFNGLTEXPARAMETERIVPROC glTexParameteriv;
PFNGLTEXIMAGE1DPROC glTexImage1D;
PFNGLTEXIMAGE2DPROC glTexImage2D;
PFNGLDRAWBUFFERPROC glDrawBuffer;
PFNGLCLEARPROC glClear;
PFNGLCLEARCOLORPROC glClearColor;
PFNGLCLEARSTENCILPROC glClearStencil;
PFNGLCLEARDEPTHPROC glClearDepth;
PFNGLSTENCILMASKPROC glStencilMask;
PFNGLCOLORMASKPROC glColorMask;
PFNGLDEPTHMASKPROC glDepthMask;
PFNGLDISABLEPROC glDisable;
PFNGLENABLEPROC glEnable;
PFNGLFINISHPROC glFinish;
PFNGLFLUSHPROC glFlush;
PFNGLBLENDFUNCPROC glBlendFunc;
PFNGLLOGICOPPROC glLogicOp;
PFNGLSTENCILFUNCPROC glStencilFunc;
PFNGLSTENCILOPPROC glStencilOp;
PFNGLDEPTHFUNCPROC glDepthFunc;
PFNGLPIXELSTOREFPROC glPixelStoref;
PFNGLPIXELSTOREIPROC glPixelStorei;
PFNGLREADBUFFERPROC glReadBuffer;
PFNGLREADPIXELSPROC glReadPixels;
PFNGLGETBOOLEANVPROC glGetBooleanv;
PFNGLGETDOUBLEVPROC glGetDoublev;
PFNGLGETERRORPROC glGetError;
PFNGLGETFLOATVPROC glGetFloatv;
PFNGLGETINTEGERVPROC glGetIntegerv;
PFNGLGETSTRINGPROC glGetString;
PFNGLGETTEXIMAGEPROC glGetTexImage;
PFNGLGETTEXPARAMETERFVPROC glGetTexParameterfv;
PFNGLGETTEXPARAMETERIVPROC glGetTexParameteriv;
PFNGLGETTEXLEVELPARAMETERFVPROC glGetTexLevelParameterfv;
PFNGLGETTEXLEVELPARAMETERIVPROC glGetTexLevelParameteriv;
PFNGLISENABLEDPROC glIsEnabled;
PFNGLDEPTHRANGEPROC glDepthRange;
PFNGLVIEWPORTPROC glViewport;
#endif

#ifdef GL_VERSION_1_1
PFNGLDRAWARRAYSPROC glDrawArrays;
PFNGLDRAWELEMENTSPROC glDrawElements;
PFNGLGETPOINTERVPROC glGetPointerv;
PFNGLPOLYGONOFFSETPROC glPolygonOffset;
PFNGLCOPYTEXIMAGE1DPROC glCopyTexImage1D;
PFNGLCOPYTEXIMAGE2DPROC glCopyTexImage2D;
PFNGLCOPYTEXSUBIMAGE1DPROC glCopyTexSubImage1D;
PFNGLCOPYTEXSUBIMAGE2DPROC glCopyTexSubImage2D;
PFNGLTEXSUBIMAGE1DPROC glTexSubImage1D;
PFNGLTEXSUBIMAGE2DPROC glTexSubImage2D;
PFNGLBINDTEXTUREPROC glBindTexture;
PFNGLDELETETEXTURESPROC glDeleteTextures;
PFNGLGENTEXTURESPROC glGenTextures;
PFNGLISTEXTUREPROC glIsTexture;
#endif

#ifdef GL_VERSION_1_2
PFNGLBLENDCOLORPROC glBlendColor;
PFNGLBLENDEQUATIONPROC glBlendEquation;
PFNGLDRAWRANGEELEMENTSPROC glDrawRangeElements;
PFNGLTEXIMAGE3DPROC glTexImage3D;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D;
PFNGLCOPYTEXSUBIMAGE3DPROC glCopyTexSubImage3D;
#endif

#ifdef GL_VERSION_1_3
PFNGLACTIVETEXTUREPROC glActiveTexture;
PFNGLSAMPLECOVERAGEPROC glSampleCoverage;
PFNGLCOMPRESSEDTEXIMAGE3DPROC glCompressedTexImage3D;
PFNGLCOMPRESSEDTEXIMAGE2DPROC glCompressedTexImage2D;
PFNGLCOMPRESSEDTEXIMAGE1DPROC glCompressedTexImage1D;
PFNGLCOMPRESSEDTEXSUBIMAGE3DPROC glCompressedTexSubImage3D;
PFNGLCOMPRESSEDTEXSUBIMAGE2DPROC glCompressedTexSubImage2D;
PFNGLCOMPRESSEDTEXSUBIMAGE1DPROC glCompressedTexSubImage1D;
PFNGLGETCOMPRESSEDTEXIMAGEPROC glGetCompressedTexImage;
#endif

#ifdef GL_VERSION_1_4
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate;
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays;
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements;
PFNGLPOINTPARAMETERFPROC glPointParameterf;
PFNGLPOINTPARAMETERFVPROC glPointParameterfv;
PFNGLPOINTPARAMETERIPROC glPointParameteri;
PFNGLPOINTPARAMETERIVPROC glPointParameteriv;
#endif

#ifdef GL_VERSION_1_5
PFNGLGENQUERIESPROC glGenQueries;
PFNGLDELETEQUERIESPROC glDeleteQueries;
PFNGLISQUERYPROC glIsQuery;
PFNGLBEGINQUERYPROC glBeginQuery;
PFNGLENDQUERYPROC glEndQuery;
PFNGLGETQUERYIVPROC glGetQueryiv;
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv;
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLDELETEBUFFERSPROC glDeleteBuffers;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLISBUFFERPROC glIsBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLBUFFERSUBDATAPROC glBufferSubData;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData;
PFNGLMAPBUFFERPROC glMapBuffer;
PFNGLUNMAPBUFFERPROC glUnmapBuffer;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv;
PFNGLGETBUFFERPOINTERVPROC glGetBufferPointerv;
#endif

#ifdef GL_VERSION_2_0
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate;
PFNGLDRAWBUFFERSPROC glDrawBuffers;
PFNGLSTENCILOPSEPARATEPROC glStencilOpSeparate;
PFNGLSTENCILFUNCSEPARATEPROC glStencilFuncSeparate;
PFNGLSTENCILMASKSEPARATEPROC glStencilMaskSeparate;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLBINDATTRIBLOCATIONPROC glBindAttribLocation;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLDELETEPROGRAMPROC glDeleteProgram;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLGETACTIVEATTRIBPROC glGetActiveAttrib;
PFNGLGETACTIVEUNIFORMPROC glGetActiveUniform;
PFNGLGETATTACHEDSHADERSPROC glGetAttachedShaders;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETSHADERSOURCEPROC glGetShaderSource;
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation;
PFNGLGETUNIFORMFVPROC glGetUniformfv;
PFNGLGETUNIFORMIVPROC glGetUniformiv;
PFNGLGETVERTEXATTRIBDVPROC glGetVertexAttribdv;
PFNGLGETVERTEXATTRIBFVPROC glGetVertexAttribfv;
PFNGLGETVERTEXATTRIBIVPROC glGetVertexAttribiv;
PFNGLGETVERTEXATTRIBPOINTERVPROC glGetVertexAttribPointerv;
PFNGLISPROGRAMPROC glIsProgram;
PFNGLISSHADERPROC glIsShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLUNIFORM1FPROC glUniform1f;
PFNGLUNIFORM2FPROC glUniform2f;
PFNGLUNIFORM3FPROC glUniform3f;
PFNGLUNIFORM4FPROC glUniform4f;
PFNGLUNIFORM1IPROC glUniform1i;
PFNGLUNIFORM2IPROC glUniform2i;
PFNGLUNIFORM3IPROC glUniform3i;
PFNGLUNIFORM4IPROC glUniform4i;
PFNGLUNIFORM1FVPROC glUniform1fv;
PFNGLUNIFORM2FVPROC glUniform2fv;
PFNGLUNIFORM3FVPROC glUniform3fv;
PFNGLUNIFORM4FVPROC glUniform4fv;
PFNGLUNIFORM1IVPROC glUniform1iv;
PFNGLUNIFORM2IVPROC glUniform2iv;
PFNGLUNIFORM3IVPROC glUniform3iv;
PFNGLUNIFORM4IVPROC glUniform4iv;
PFNGLUNIFORMMATRIX2FVPROC glUniformMatrix2fv;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv;
PFNGLVALIDATEPROGRAMPROC glValidateProgram;
PFNGLVERTEXATTRIB1DPROC glVertexAttrib1d;
PFNGLVERTEXATTRIB1DVPROC glVertexAttrib1dv;
PFNGLVERTEXATTRIB1FPROC glVertexAttrib1f;
PFNGLVERTEXATTRIB1FVPROC glVertexAttrib1fv;
PFNGLVERTEXATTRIB1SPROC glVertexAttrib1s;
PFNGLVERTEXATTRIB1SVPROC glVertexAttrib1sv;
PFNGLVERTEXATTRIB2DPROC glVertexAttrib2d;
PFNGLVERTEXATTRIB2DVPROC glVertexAttrib2dv;
PFNGLVERTEXATTRIB2FPROC glVertexAttrib2f;
PFNGLVERTEXATTRIB2FVPROC glVertexAttrib2fv;
PFNGLVERTEXATTRIB2SPROC glVertexAttrib2s;
PFNGLVERTEXATTRIB2SVPROC glVertexAttrib2sv;
PFNGLVERTEXATTRIB3DPROC glVertexAttrib3d;
PFNGLVERTEXATTRIB3DVPROC glVertexAttrib3dv;
PFNGLVERTEXATTRIB3FPROC glVertexAttrib3f;
PFNGLVERTEXATTRIB3FVPROC glVertexAttrib3fv;
PFNGLVERTEXATTRIB3SPROC glVertexAttrib3s;
PFNGLVERTEXATTRIB3SVPROC glVertexAttrib3sv;
PFNGLVERTEXATTRIB4NBVPROC glVertexAttrib4Nbv;
PFNGLVERTEXATTRIB4NIVPROC glVertexAttrib4Niv;
PFNGLVERTEXATTRIB4NSVPROC glVertexAttrib4Nsv;
PFNGLVERTEXATTRIB4NUBPROC glVertexAttrib4Nub;
PFNGLVERTEXATTRIB4NUBVPROC glVertexAttrib4Nubv;
PFNGLVERTEXATTRIB4NUIVPROC glVertexAttrib4Nuiv;
PFNGLVERTEXATTRIB4NUSVPROC glVertexAttrib4Nusv;
PFNGLVERTEXATTRIB4BVPROC glVertexAttrib4bv;
PFNGLVERTEXATTRIB4DPROC glVertexAttrib4d;
PFNGLVERTEXATTRIB4DVPROC glVertexAttrib4dv;
PFNGLVERTEXATTRIB4FPROC glVertexAttrib4f;
PFNGLVERTEXATTRIB4FVPROC glVertexAttrib4fv;
PFNGLVERTEXATTRIB4IVPROC glVertexAttrib4iv;
PFNGLVERTEXATTRIB4SPROC glVertexAttrib4s;
PFNGLVERTEXATTRIB4SVPROC glVertexAttrib4sv;
PFNGLVERTEXATTRIB4UBVPROC glVertexAttrib4ubv;
PFNGLVERTEXATTRIB4UIVPROC glVertexAttrib4uiv;
PFNGLVERTEXATTRIB4USVPROC glVertexAttrib4usv;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
#endif

#ifdef GL_VERSION_2_1
PFNGLUNIFORMMATRIX2X3FVPROC glUniformMatrix2x3fv;
PFNGLUNIFORMMATRIX3X2FVPROC glUniformMatrix3x2fv;
PFNGLUNIFORMMATRIX2X4FVPROC glUniformMatrix2x4fv;
PFNGLUNIFORMMATRIX4X2FVPROC glUniformMatrix4x2fv;
PFNGLUNIFORMMATRIX3X4FVPROC glUniformMatrix3x4fv;
PFNGLUNIFORMMATRIX4X3FVPROC glUniformMatrix4x3fv;
#endif

#ifdef GL_VERSION_3_0
PFNGLCOLORMASKIPROC glColorMaski;
PFNGLGETBOOLEANI_VPROC glGetBooleani_v;
PFNGLGETINTEGERI_VPROC glGetIntegeri_v;
PFNGLENABLEIPROC glEnablei;
PFNGLDISABLEIPROC glDisablei;
PFNGLISENABLEDIPROC glIsEnabledi;
PFNGLBEGINTRANSFORMFEEDBACKPROC glBeginTransformFeedback;
PFNGLENDTRANSFORMFEEDBACKPROC glEndTransformFeedback;
PFNGLBINDBUFFERRANGEPROC glBindBufferRange;
PFNGLBINDBUFFERBASEPROC glBindBufferBase;
PFNGLTRANSFORMFEEDBACKVARYINGSPROC glTransformFeedbackVaryings;
PFNGLGETTRANSFORMFEEDBACKVARYINGPROC glGetTransformFeedbackVarying;
PFNGLCLAMPCOLORPROC glClampColor;
PFNGLBEGINCONDITIONALRENDERPROC glBeginConditionalRender;
PFNGLENDCONDITIONALRENDERPROC glEndConditionalRender;
PFNGLVERTEXATTRIBIPOINTERPROC glVertexAttribIPointer;
PFNGLGETVERTEXATTRIBIIVPROC glGetVertexAttribIiv;
PFNGLGETVERTEXATTRIBIUIVPROC glGetVertexAttribIuiv;
PFNGLVERTEXATTRIBI1IPROC glVertexAttribI1i;
PFNGLVERTEXATTRIBI2IPROC glVertexAttribI2i;
PFNGLVERTEXATTRIBI3IPROC glVertexAttribI3i;
PFNGLVERTEXATTRIBI4IPROC glVertexAttribI4i;
PFNGLVERTEXATTRIBI1UIPROC glVertexAttribI1ui;
PFNGLVERTEXATTRIBI2UIPROC glVertexAttribI2ui;
PFNGLVERTEXATTRIBI3UIPROC glVertexAttribI3ui;
PFNGLVERTEXATTRIBI4UIPROC glVertexAttribI4ui;
PFNGLVERTEXATTRIBI1IVPROC glVertexAttribI1iv;
PFNGLVERTEXATTRIBI2IVPROC glVertexAttribI2iv;
PFNGLVERTEXATTRIBI3IVPROC glVertexAttribI3iv;
PFNGLVERTEXATTRIBI4IVPROC glVertexAttribI4iv;
PFNGLVERTEXATTRIBI1UIVPROC glVertexAttribI1uiv;
PFNGLVERTEXATTRIBI2UIVPROC glVertexAttribI2uiv;
PFNGLVERTEXATTRIBI3UIVPROC glVertexAttribI3uiv;
PFNGLVERTEXATTRIBI4UIVPROC glVertexAttribI4uiv;
PFNGLVERTEXATTRIBI4BVPROC glVertexAttribI4bv;
PFNGLVERTEXATTRIBI4SVPROC glVertexAttribI4sv;
PFNGLVERTEXATTRIBI4UBVPROC glVertexAttribI4ubv;
PFNGLVERTEXATTRIBI4USVPROC glVertexAttribI4usv;
PFNGLGETUNIFORMUIVPROC glGetUniformuiv;
PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation;
PFNGLGETFRAGDATALOCATIONPROC glGetFragDataLocation;
PFNGLUNIFORM1UIPROC glUniform1ui;
PFNGLUNIFORM2UIPROC glUniform2ui;
PFNGLUNIFORM3UIPROC glUniform3ui;
PFNGLUNIFORM4UIPROC glUniform4ui;
PFNGLUNIFORM1UIVPROC glUniform1uiv;
PFNGLUNIFORM2UIVPROC glUniform2uiv;
PFNGLUNIFORM3UIVPROC glUniform3uiv;
PFNGLUNIFORM4UIVPROC glUniform4uiv;
PFNGLTEXPARAMETERIIVPROC glTexParameterIiv;
PFNGLTEXPARAMETERIUIVPROC glTexParameterIuiv;
PFNGLGETTEXPARAMETERIIVPROC glGetTexParameterIiv;
PFNGLGETTEXPARAMETERIUIVPROC glGetTexParameterIuiv;
PFNGLCLEARBUFFERIVPROC glClearBufferiv;
PFNGLCLEARBUFFERUIVPROC glClearBufferuiv;
PFNGLCLEARBUFFERFVPROC glClearBufferfv;
PFNGLCLEARBUFFERFIPROC glClearBufferfi;
PFNGLGETSTRINGIPROC glGetStringi;
#endif

#ifdef GL_VERSION_3_1
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced;
PFNGLTEXBUFFERPROC glTexBuffer;
PFNGLPRIMITIVERESTARTINDEXPROC glPrimitiveRestartIndex;
#endif

#ifdef GL_VERSION_3_2
PFNGLGETINTEGER64I_VPROC glGetInteger64i_v;
PFNGLGETBUFFERPARAMETERI64VPROC glGetBufferParameteri64v;
PFNGLFRAMEBUFFERTEXTUREPROC glFramebufferTexture;
#endif

#ifdef GL_VERSION_3_3
PFNGLVERTEXATTRIBDIVISORPROC glVertexAttribDivisor;
#endif

#ifdef GL_ARB_framebuffer_object
PFNGLISRENDERBUFFERPROC glIsRenderbuffer;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage;
PFNGLGETRENDERBUFFERPARAMETERIVPROC glGetRenderbufferParameteriv;
PFNGLISFRAMEBUFFERPROC glIsFramebuffer;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus;
PFNGLFRAMEBUFFERTEXTURE1DPROC glFramebufferTexture1D;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D;
PFNGLFRAMEBUFFERTEXTURE3DPROC glFramebufferTexture3D;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer;
PFNGLGETFRAMEBUFFERATTACHMENTPARAMETERIVPROC glGetFramebufferAttachmentParameteriv;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap;
PFNGLBLITFRAMEBUFFERPROC glBlitFramebuffer;
PFNGLRENDERBUFFERSTORAGEMULTISAMPLEPROC glRenderbufferStorageMultisample;
PFNGLFRAMEBUFFERTEXTURELAYERPROC glFramebufferTextureLayer;
#endif

#ifdef GL_ARB_map_buffer_range
PFNGLMAPBUFFERRANGEPROC glMapBufferRange;
PFNGLFLUSHMAPPEDBUFFERRANGEPROC glFlushMappedBufferRange;
#endif

#ifdef GL_ARB_vertex_array_object
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLISVERTEXARRAYPROC glIsVertexArray;
#endif

#ifdef GL_ARB_uniform_buffer_object
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices;
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv;
PFNGLGETACTIVEUNIFORMNAMEPROC glGetActiveUniformName;
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv;
PFNGLGETACTIVEUNIFORMBLOCKNAMEPROC glGetActiveUniformBlockName;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding;
#endif

#ifdef GL_ARB_copy_buffer
PFNGLCOPYBUFFERSUBDATAPROC glCopyBufferSubData;
#endif

#ifdef GL_ARB_draw_elements_base_vertex
PFNGLDRAWELEMENTSBASEVERTEXPROC glDrawElementsBaseVertex;
PFNGLDRAWRANGEELEMENTSBASEVERTEXPROC glDrawRangeElementsBaseVertex;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXPROC glDrawElementsInstancedBaseVertex;
PFNGLMULTIDRAWELEMENTSBASEVERTEXPROC glMultiDrawElementsBaseVertex;
#endif

#ifdef GL_ARB_provoking_vertex
PFNGLPROVOKINGVERTEXPROC glProvokingVertex;
#endif

#ifdef GL_ARB_sync
PFNGLFENCESYNCPROC glFenceSync;
PFNGLISSYNCPROC glIsSync;
PFNGLDELETESYNCPROC glDeleteSync;
PFNGLCLIENTWAITSYNCPROC glClientWaitSync;
PFNGLWAITSYNCPROC glWaitSync;
PFNGLGETINTEGER64VPROC glGetInteger64v;
PFNGLGETSYNCIVPROC glGetSynciv;
#endif

#ifdef GL_ARB_texture_multisample
PFNGLTEXIMAGE2DMULTISAMPLEPROC glTexImage2DMultisample;
PFNGLTEXIMAGE3DMULTISAMPLEPROC glTexImage3DMultisample;
PFNGLGETMULTISAMPLEFVPROC glGetMultisamplefv;
PFNGLSAMPLEMASKIPROC glSampleMaski;
#endif

#ifdef GL_ARB_blend_func_extended
PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glBindFragDataLocationIndexed;
PFNGLGETFRAGDATAINDEXPROC glGetFragDataIndex;
#endif

#ifdef GL_ARB_sampler_objects
PFNGLGENSAMPLERSPROC glGenSamplers;
PFNGLDELETESAMPLERSPROC glDeleteSamplers;
PFNGLISSAMPLERPROC glIsSampler;
PFNGLBINDSAMPLERPROC glBindSampler;
PFNGLSAMPLERPARAMETERIPROC glSamplerParameteri;
PFNGLSAMPLERPARAMETERIVPROC glSamplerParameteriv;
PFNGLSAMPLERPARAMETERFPROC glSamplerParameterf;
PFNGLSAMPLERPARAMETERFVPROC glSamplerParameterfv;
PFNGLSAMPLERPARAMETERIIVPROC glSamplerParameterIiv;
PFNGLSAMPLERPARAMETERIUIVPROC glSamplerParameterIuiv;
PFNGLGETSAMPLERPARAMETERIVPROC glGetSamplerParameteriv;
PFNGLGETSAMPLERPARAMETERIIVPROC glGetSamplerParameterIiv;
PFNGLGETSAMPLERPARAMETERFVPROC glGetSamplerParameterfv;
PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv;
#endif

#ifdef GL_ARB_timer_query
PFNGLQUERYCOUNTERPROC glQueryCounter;
PFNGLGETQUERYOBJECTI64VPROC glGetQueryObjecti64v;
PFNGLGETQUERYOBJECTUI64VPROC glGetQueryObjectui64v;
#endif

#ifdef GL_ARB_vertex_type_2_10_10_10_rev
PFNGLVERTEXP2UIPROC glVertexP2ui;
PFNGLVERTEXP2UIVPROC glVertexP2uiv;
PFNGLVERTEXP3UIPROC glVertexP3ui;
PFNGLVERTEXP3UIVPROC glVertexP3uiv;
PFNGLVERTEXP4UIPROC glVertexP4ui;
PFNGLVERTEXP4UIVPROC glVertexP4uiv;
PFNGLTEXCOORDP1UIPROC glTexCoordP1ui;
PFNGLTEXCOORDP1UIVPROC glTexCoordP1uiv;
PFNGLTEXCOORDP2UIPROC glTexCoordP2ui;
PFNGLTEXCOORDP2UIVPROC glTexCoordP2uiv;
PFNGLTEXCOORDP3UIPROC glTexCoordP3ui;
PFNGLTEXCOORDP3UIVPROC glTexCoordP3uiv;
PFNGLTEXCOORDP4UIPROC glTexCoordP4ui;
PFNGLTEXCOORDP4UIVPROC glTexCoordP4uiv;
PFNGLMULTITEXCOORDP1UIPROC glMultiTexCoordP1ui;
PFNGLMULTITEXCOORDP1UIVPROC glMultiTexCoordP1uiv;
PFNGLMULTITEXCOORDP2UIPROC glMultiTexCoordP2ui;
PFNGLMULTITEXCOORDP2UIVPROC glMultiTexCoordP2uiv;
PFNGLMULTITEXCOORDP3UIPROC glMultiTexCoordP3ui;
PFNGLMULTITEXCOORDP3UIVPROC glMultiTexCoordP3uiv;
PFNGLMULTITEXCOORDP4UIPROC glMultiTexCoordP4ui;
PFNGLMULTITEXCOORDP4UIVPROC glMultiTexCoordP4uiv;
PFNGLNORMALP3UIPROC glNormalP3ui;
PFNGLNORMALP3UIVPROC glNormalP3uiv;
PFNGLCOLORP3UIPROC glColorP3ui;
PFNGLCOLORP3UIVPROC glColorP3uiv;
PFNGLCOLORP4UIPROC glColorP4ui;
PFNGLCOLORP4UIVPROC glColorP4uiv;
PFNGLSECONDARYCOLORP3UIPROC glSecondaryColorP3ui;
PFNGLSECONDARYCOLORP3UIVPROC glSecondaryColorP3uiv;
PFNGLVERTEXATTRIBP1UIPROC glVertexAttribP1ui;
PFNGLVERTEXATTRIBP1UIVPROC glVertexAttribP1uiv;
PFNGLVERTEXATTRIBP2UIPROC glVertexAttribP2ui;
PFNGLVERTEXATTRIBP2UIVPROC glVertexAttribP2uiv;
PFNGLVERTEXATTRIBP3UIPROC glVertexAttribP3ui;
PFNGLVERTEXATTRIBP3UIVPROC glVertexAttribP3uiv;
PFNGLVERTEXATTRIBP4UIPROC glVertexAttribP4ui;
PFNGLVERTEXATTRIBP4UIVPROC glVertexAttribP4uiv;
#endif

bool OpenGLLoadLibrary(const HorseRadish::hChar *openGLLibraryName)
{
	wchar_t openGLLibraryNameWChar[128];

	//se isto já está carregado
	if (openGLModule != nullptr)
		return false;

	//tenho de converter o nome do modulo de OpenGL para WideChar
	HorseRadish::UTF::ConvertUTF8To(openGLLibraryName, HorseRadish::UTF::Windows, openGLLibraryNameWChar, sizeof(openGLLibraryNameWChar));

	//carrego a libraria
	openGLModule = LoadLibrary(openGLLibraryNameWChar);
	return (openGLModule != nullptr);
}

bool OpenGLUnloadLibrary(void)
{
	//se nunca cheguei a carregar a libraria
	if (openGLModule == nullptr)
		return false;
 
	//basta descarregar a libraria
	FreeLibrary(openGLModule);
	openGLModule = nullptr;
	return true;
}

bool OpenGLGetProcs(void)
{
	PFNWGLGETPROCADDRESSPROC ptrWGlGetProcAddress;

	//preciso que isto esteja carregado
	if (openGLModule == nullptr)
		return false;

	//tento obter este ponteiro para a função
	ptrWGlGetProcAddress = (PFNWGLGETPROCADDRESSPROC)GetProcAddress(openGLModule, "wglGetProcAddress");
	if (ptrWGlGetProcAddress == nullptr)
		return false;
 
	//carrego tudo do OpenGL e se algo correu mal
	if (loadGLFunctions(openGLModule, ptrWGlGetProcAddress) == false)
	{
		FreeLibrary(openGLModule);
		openGLModule = nullptr;
		return false;
	}

	//correu tudo bem
	return true;
}

}//namespace OpenGL
}//namespace HorseRadish