/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109716-g757218564d-20230129"
#endif /* AVUTIL_FFVERSION_H */
