/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-122791-g52b676bb29-20260219"
#endif /* AVUTIL_FFVERSION_H */
