#define TINYEXR_IMPLEMENTATION

#define TINYEXR_USE_MINIZ 1
#define TINYEXR_USE_STB_ZLIB 0
#define TINYEXR_USE_PIZ 1
#define TINYEXR_USE_ZFP 0
#define TINYEXR_USE_THREAD 0
#define TINYEXR_USE_OPENMP 0

#include <tinyexr.h>
